image: python:3.9

before_script:
  - pip install tox

stages:
  - style
  - build
  - test
  - documentation
  - deploy

# style
style:
  stage: style
  image: python:3.9
  script:
    - tox -vv
  variables:
    TOXENV: flake8,black

# build
build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# test
py39:linux:
  stage: test
  script:
    - echo "Demo" > Demo.txt
  artifacts: 
    paths: 
      - ./Demo.txt
      # - ./PoC Tutorial_GrowOptimized.esdl
    expire_in: 1 week
  image: python:3.9
  variables:
    TOXENV: py39

# documentation
pages:
  stage: documentation
  before_script:
    - echo "documentation"
  script:
    - pip install -e .
    - cd docs
    - pip install -r requirements.txt
    - make html
    - mv _build/html ../public
    - cd ..
  artifacts:
    paths:
      - public
  only:
    - master

# deploy
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - pip install twine
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
    - tags
